name: Python Test Suite

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Setup Test Environment
        uses: ./.github/workflows/setup_test_environment.yml 

      - name: Run unit tests
        run: poetry run pytest tests/unit 

  integration_tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' # Run only on pull requests

    steps:
      - name: Setup Test Environment
        uses: ./.github/workflows/setup_test_environment.yml 

      - name: Run integration tests
        run: poetry run pytest tests/integration 
