name: Python Test Suite

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  unit_tests:
    name: Unit Tests
    uses: ./.github/workflows/test_env_setup_and_run_workflow.yml # Calls reusable workflow for setup and test execution
    with:
      test_command: poetry run pytest tests/unit # Passes unit test command as input

  integration_tests:
    name: Integration Tests
    uses: ./.github/workflows/test_env_setup_and_run_workflow.yml # Calls reusable workflow for setup and test execution
    with:
      test_command: poetry run pytest tests/integration # Passes integration test command as input
